services:
  lylink:
    image: wlczak/lylink:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ./:/var/www/html
    ports:
      - "1592:80"
    command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html/public_html"]