services:
    lylink:
        image: wlczak/lylink:latest
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            # - ./:/var/www/html # For local development
            - ./db:/var/www/html/db
            - ./config/:/var/www/html/config/
            - ./logs/:/var/www/html/logs/
        ports:
            - "1592:80"
        init: true
        command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html/public_html"]
        networks:
            - lylink-net

networks:
    lylink-net:
        driver: bridge
