###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
    webserver:
        image: wlczak/lylink-nginx
        working_dir: /var/www/html
        labels:
            - com.centurylinklabs.watchtower.enable=true
        # volumes:
            # - '.:/var/www/html'
        ports:
            - '1592:80'

    php-fpm:
        image: wlczak/lylink
        working_dir: /var/www/html
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            # - '.:/var/www/html'
            - ./db:/var/www/html/db
            - ./config/:/var/www/html/config/
            - ./logs/:/var/www/html/logs/
