services:
  lylink:
    build:
      context: ../
      dockerfile: Dockerfile
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ../:/var/www/html # For local development
      # - ./lyrics.db:/var/www/html/lyrics.db
      # - ./.env:/var/www/html/.env
    ports:
      - "1592:80"
    init: true
    command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html/public_html"]
    networks:
      - lylink-net

networks:
  lylink-net:
    driver: bridge